name: lint

on:
  pull_request:
    paths:
    - 'src/**'
    
jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Super-Linter
      uses: github/super-linter@v4.9.7
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
